export const issues = [
  {
    "id": "ISS-001",
    "title": "Street flooding",
    "description": "Posing a risk to pedestrians.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 70,
    "status": "in-progress",
    "lat": 18.53838,
    "lng": 73.867374,
    "reportedAt": "2025-06-08"
  },
  {
    "id": "ISS-002",
    "title": "Pothole on road",
    "description": "Creating hygiene and sanitation issues.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 14,
    "status": "unresolved",
    "lat": 18.524701,
    "lng": 73.853978,
    "reportedAt": "2025-09-12"
  },
  {
    "id": "ISS-003",
    "title": "Pothole on road",
    "description": "Resulting in foul smell in locality.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 79,
    "status": "in-progress",
    "lat": 18.533917,
    "lng": 73.855655,
    "reportedAt": "2025-07-25"
  },
  {
    "id": "ISS-004",
    "title": "Damaged sidewalk",
    "description": "Posing a risk to pedestrians.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 45,
    "status": "unresolved",
    "lat": 18.529177,
    "lng": 73.868548,
    "reportedAt": "2025-08-21"
  },
  {
    "id": "ISS-005",
    "title": "Illegal dumping",
    "description": "Causing power disruptions.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 40,
    "status": "unresolved",
    "lat": 18.52217,
    "lng": 73.859419,
    "reportedAt": "2025-09-12"
  },
  {
    "id": "ISS-006",
    "title": "Water leakage",
    "description": "Affecting water supply in nearby areas.",
    "category": "Electricity",
    "severity": "high",
    "upvotes": 24,
    "status": "unresolved",
    "lat": 18.532383,
    "lng": 73.850203,
    "reportedAt": "2025-05-18"
  },
  {
    "id": "ISS-007",
    "title": "Streetlight not working",
    "description": "Making the road unsafe for vehicles.",
    "category": "Roads",
    "severity": "medium",
    "upvotes": 43,
    "status": "in-progress",
    "lat": 18.532535,
    "lng": 73.863408,
    "reportedAt": "2025-08-10"
  },
  {
    "id": "ISS-008",
    "title": "Clogged drainage",
    "description": "Problem persists for weeks without resolution.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 49,
    "status": "in-progress",
    "lat": 18.525651,
    "lng": 73.860245,
    "reportedAt": "2025-04-02"
  },
  {
    "id": "ISS-009",
    "title": "Open manhole cover",
    "description": "Causing power disruptions.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 84,
    "status": "resolved",
    "lat": 18.532234,
    "lng": 73.858888,
    "reportedAt": "2025-06-16"
  },
  {
    "id": "ISS-010",
    "title": "Damaged sidewalk",
    "description": "Causing safety concerns for residents.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 26,
    "status": "in-progress",
    "lat": 18.529914,
    "lng": 73.860583,
    "reportedAt": "2025-07-17"
  },
  {
    "id": "ISS-011",
    "title": "Leaking tanker",
    "description": "Posing a risk to pedestrians.",
    "category": "Sanitation",
    "severity": "low",
    "upvotes": 80,
    "status": "resolved",
    "lat": 18.532902,
    "lng": 73.852485,
    "reportedAt": "2025-05-28"
  },
  {
    "id": "ISS-012",
    "title": "Uncollected garbage bins",
    "description": "Problem persists for weeks without resolution.",
    "category": "Water Supply",
    "severity": "medium",
    "upvotes": 78,
    "status": "unresolved",
    "lat": 18.528765,
    "lng": 73.861032,
    "reportedAt": "2025-03-24"
  },
  {
    "id": "ISS-013",
    "title": "Clogged drainage",
    "description": "Creating hygiene and sanitation issues.",
    "category": "Roads",
    "severity": "high",
    "upvotes": 45,
    "status": "unresolved",
    "lat": 18.539439,
    "lng": 73.851277,
    "reportedAt": "2025-05-30"
  },
  {
    "id": "ISS-014",
    "title": "Open manhole cover",
    "description": "Making the road unsafe for vehicles.",
    "category": "Roads",
    "severity": "high",
    "upvotes": 68,
    "status": "in-progress",
    "lat": 18.537054,
    "lng": 73.859737,
    "reportedAt": "2025-07-29"
  },
  {
    "id": "ISS-015",
    "title": "Water leakage",
    "description": "Causing power disruptions.",
    "category": "Water Supply",
    "severity": "medium",
    "upvotes": 9,
    "status": "resolved",
    "lat": 18.527964,
    "lng": 73.85648,
    "reportedAt": "2025-06-23"
  },
  {
    "id": "ISS-016",
    "title": "Water leakage",
    "description": "Making the road unsafe for vehicles.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 42,
    "status": "resolved",
    "lat": 18.539164,
    "lng": 73.864446,
    "reportedAt": "2025-05-13"
  },
  {
    "id": "ISS-017",
    "title": "Leaking tanker",
    "description": "Leading to traffic congestion.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 22,
    "status": "unresolved",
    "lat": 18.538591,
    "lng": 73.85831,
    "reportedAt": "2025-06-30"
  },
  {
    "id": "ISS-018",
    "title": "Illegal dumping",
    "description": "Causing power disruptions.",
    "category": "Electricity",
    "severity": "high",
    "upvotes": 82,
    "status": "resolved",
    "lat": 18.521549,
    "lng": 73.863929,
    "reportedAt": "2025-04-03"
  },
  {
    "id": "ISS-019",
    "title": "Accumulated debris",
    "description": "Reported multiple times by residents.",
    "category": "Electricity",
    "severity": "medium",
    "upvotes": 55,
    "status": "resolved",
    "lat": 18.537024,
    "lng": 73.860468,
    "reportedAt": "2025-04-29"
  },
  {
    "id": "ISS-020",
    "title": "Transformer sparks",
    "description": "Posing a risk to pedestrians.",
    "category": "Water Supply",
    "severity": "high",
    "upvotes": 34,
    "status": "resolved",
    "lat": 18.527419,
    "lng": 73.869827,
    "reportedAt": "2025-04-10"
  },
  {
    "id": "ISS-021",
    "title": "Damaged traffic sign",
    "description": "Affecting water supply in nearby areas.",
    "category": "Sanitation",
    "severity": "low",
    "upvotes": 70,
    "status": "in-progress",
    "lat": 18.524659,
    "lng": 73.862342,
    "reportedAt": "2025-07-13"
  },
  {
    "id": "ISS-022",
    "title": "Illegal dumping",
    "description": "Causing safety concerns for residents.",
    "category": "Sanitation",
    "severity": "high",
    "upvotes": 95,
    "status": "in-progress",
    "lat": 18.527733,
    "lng": 73.858272,
    "reportedAt": "2025-09-09"
  },
  {
    "id": "ISS-023",
    "title": "Streetlight not working",
    "description": "Leading to traffic congestion.",
    "category": "Water Supply",
    "severity": "medium",
    "upvotes": 57,
    "status": "unresolved",
    "lat": 18.522937,
    "lng": 73.85133,
    "reportedAt": "2025-09-09"
  },
  {
    "id": "ISS-024",
    "title": "Accumulated debris",
    "description": "Making the road unsafe for vehicles.",
    "category": "Water Supply",
    "severity": "medium",
    "upvotes": 19,
    "status": "resolved",
    "lat": 18.529604,
    "lng": 73.858765,
    "reportedAt": "2025-09-06"
  },
  {
    "id": "ISS-025",
    "title": "Uncollected garbage bins",
    "description": "Making the road unsafe for vehicles.",
    "category": "Electricity",
    "severity": "medium",
    "upvotes": 40,
    "status": "in-progress",
    "lat": 18.520886,
    "lng": 73.857473,
    "reportedAt": "2025-04-22"
  },
  {
    "id": "ISS-026",
    "title": "Loose overhead wire",
    "description": "Reported multiple times by residents.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 8,
    "status": "in-progress",
    "lat": 18.537996,
    "lng": 73.857213,
    "reportedAt": "2025-08-03"
  },
  {
    "id": "ISS-027",
    "title": "Overhead wire hazard",
    "description": "Posing a risk to pedestrians.",
    "category": "Water Supply",
    "severity": "medium",
    "upvotes": 56,
    "status": "in-progress",
    "lat": 18.524604,
    "lng": 73.854162,
    "reportedAt": "2025-07-14"
  },
  {
    "id": "ISS-028",
    "title": "Drinking water contamination",
    "description": "Problem persists for weeks without resolution.",
    "category": "Sanitation",
    "severity": "high",
    "upvotes": 98,
    "status": "unresolved",
    "lat": 18.524519,
    "lng": 73.852476,
    "reportedAt": "2025-05-22"
  },
  {
    "id": "ISS-029",
    "title": "Garbage overflow",
    "description": "Making the road unsafe for vehicles.",
    "category": "Sanitation",
    "severity": "medium",
    "upvotes": 68,
    "status": "resolved",
    "lat": 18.538295,
    "lng": 73.866227,
    "reportedAt": "2025-05-28"
  },
  {
    "id": "ISS-030",
    "title": "Transformer sparks",
    "description": "Causing safety concerns for residents.",
    "category": "Roads",
    "severity": "low",
    "upvotes": 5,
    "status": "resolved",
    "lat": 18.526951,
    "lng": 73.854939,
    "reportedAt": "2025-06-25"
  },
  {
    "id": "ISS-031",
    "title": "Clogged drainage",
    "description": "Making the road unsafe for vehicles.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 87,
    "status": "resolved",
    "lat": 18.537631,
    "lng": 73.856525,
    "reportedAt": "2025-09-19"
  },
  {
    "id": "ISS-032",
    "title": "Pothole on road",
    "description": "Causing power disruptions.",
    "category": "Roads",
    "severity": "high",
    "upvotes": 18,
    "status": "in-progress",
    "lat": 18.528895,
    "lng": 73.85289,
    "reportedAt": "2025-07-17"
  },
  {
    "id": "ISS-033",
    "title": "Accumulated debris",
    "description": "Causing safety concerns for residents.",
    "category": "Water Supply",
    "severity": "low",
    "upvotes": 91,
    "status": "resolved",
    "lat": 18.538951,
    "lng": 73.868084,
    "reportedAt": "2025-07-22"
  },
  {
    "id": "ISS-034",
    "title": "Illegal dumping",
    "description": "Creating hygiene and sanitation issues.",
    "category": "Sanitation",
    "severity": "high",
    "upvotes": 68,
    "status": "in-progress",
    "lat": 18.539815,
    "lng": 73.869545,
    "reportedAt": "2025-05-29"
  },
  {
    "id": "ISS-035",
    "title": "Streetlight not working",
    "description": "Creating hygiene and sanitation issues.",
    "category": "Roads",
    "severity": "low",
    "upvotes": 73,
    "status": "in-progress",
    "lat": 18.534924,
    "lng": 73.864572,
    "reportedAt": "2025-07-13"
  },
  {
    "id": "ISS-036",
    "title": "Damaged traffic sign",
    "description": "Causing power disruptions.",
    "category": "Roads",
    "severity": "critical",
    "upvotes": 60,
    "status": "resolved",
    "lat": 18.524438,
    "lng": 73.858435,
    "reportedAt": "2025-06-17"
  },
  {
    "id": "ISS-037",
    "title": "Clogged drainage",
    "description": "Posing a risk to pedestrians.",
    "category": "Electricity",
    "severity": "high",
    "upvotes": 20,
    "status": "unresolved",
    "lat": 18.526103,
    "lng": 73.866534,
    "reportedAt": "2025-04-16"
  },
  {
    "id": "ISS-038",
    "title": "Garbage overflow",
    "description": "Leading to traffic congestion.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 80,
    "status": "in-progress",
    "lat": 18.525598,
    "lng": 73.850842,
    "reportedAt": "2025-04-02"
  },
  {
    "id": "ISS-039",
    "title": "Leaking tanker",
    "description": "Creating hygiene and sanitation issues.",
    "category": "Roads",
    "severity": "high",
    "upvotes": 61,
    "status": "resolved",
    "lat": 18.535461,
    "lng": 73.854636,
    "reportedAt": "2025-09-05"
  },
  {
    "id": "ISS-040",
    "title": "Pothole on road",
    "description": "Affecting water supply in nearby areas.",
    "category": "Electricity",
    "severity": "low",
    "upvotes": 66,
    "status": "resolved",
    "lat": 18.528492,
    "lng": 73.854591,
    "reportedAt": "2025-07-08"
  },
  {
    "id": "ISS-041",
    "title": "Transformer sparks",
    "description": "Posing a risk to pedestrians.",
    "category": "Roads",
    "severity": "medium",
    "upvotes": 14,
    "status": "resolved",
    "lat": 18.539887,
    "lng": 73.851601,
    "reportedAt": "2025-07-20"
  },
  {
    "id": "ISS-042",
    "title": "Leaking tanker",
    "description": "Making the road unsafe for vehicles.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 20,
    "status": "unresolved",
    "lat": 18.524637,
    "lng": 73.868341,
    "reportedAt": "2025-05-08"
  },
  {
    "id": "ISS-043",
    "title": "Pothole on road",
    "description": "Causing power disruptions.",
    "category": "Water Supply",
    "severity": "high",
    "upvotes": 89,
    "status": "in-progress",
    "lat": 18.525262,
    "lng": 73.856079,
    "reportedAt": "2025-04-25"
  },
  {
    "id": "ISS-044",
    "title": "Uncollected garbage bins",
    "description": "Causing safety concerns for residents.",
    "category": "Sanitation",
    "severity": "high",
    "upvotes": 64,
    "status": "in-progress",
    "lat": 18.531623,
    "lng": 73.868717,
    "reportedAt": "2025-06-17"
  },
  {
    "id": "ISS-045",
    "title": "Open manhole cover",
    "description": "Causing safety concerns for residents.",
    "category": "Sanitation",
    "severity": "critical",
    "upvotes": 64,
    "status": "in-progress",
    "lat": 18.526771,
    "lng": 73.854285,
    "reportedAt": "2025-08-10"
  },
  {
    "id": "ISS-046",
    "title": "Street flooding",
    "description": "Reported multiple times by residents.",
    "category": "Water Supply",
    "severity": "low",
    "upvotes": 34,
    "status": "in-progress",
    "lat": 18.529431,
    "lng": 73.860026,
    "reportedAt": "2025-06-06"
  },
  {
    "id": "ISS-047",
    "title": "Water leakage",
    "description": "Reported multiple times by residents.",
    "category": "Electricity",
    "severity": "low",
    "upvotes": 26,
    "status": "resolved",
    "lat": 18.520896,
    "lng": 73.859238,
    "reportedAt": "2025-07-03"
  },
  {
    "id": "ISS-048",
    "title": "Pothole on road",
    "description": "Problem persists for weeks without resolution.",
    "category": "Sanitation",
    "severity": "low",
    "upvotes": 39,
    "status": "unresolved",
    "lat": 18.538837,
    "lng": 73.853751,
    "reportedAt": "2025-05-01"
  },
  {
    "id": "ISS-049",
    "title": "Uncollected garbage bins",
    "description": "Causing safety concerns for residents.",
    "category": "Roads",
    "severity": "medium",
    "upvotes": 25,
    "status": "resolved",
    "lat": 18.522447,
    "lng": 73.859083,
    "reportedAt": "2025-05-30"
  },
  {
    "id": "ISS-050",
    "title": "Clogged drainage",
    "description": "Creating hygiene and sanitation issues.",
    "category": "Roads",
    "severity": "medium",
    "upvotes": 95,
    "status": "resolved",
    "lat": 18.527794,
    "lng": 73.867963,
    "reportedAt": "2025-04-07"
  },
  {
    "id": "ISS-051",
    "title": "Uncollected garbage bins",
    "description": "Leading to traffic congestion.",
    "category": "Sanitation",
    "severity": "critical",
    "upvotes": 62,
    "status": "resolved",
    "lat": 18.536525,
    "lng": 73.857468,
    "reportedAt": "2025-07-25"
  },
  {
    "id": "ISS-052",
    "title": "Uncollected garbage bins",
    "description": "Reported multiple times by residents.",
    "category": "Sanitation",
    "severity": "medium",
    "upvotes": 65,
    "status": "resolved",
    "lat": 18.535028,
    "lng": 73.866239,
    "reportedAt": "2025-09-16"
  },
  {
    "id": "ISS-053",
    "title": "Overhead wire hazard",
    "description": "Reported multiple times by residents.",
    "category": "Water Supply",
    "severity": "low",
    "upvotes": 76,
    "status": "in-progress",
    "lat": 18.538357,
    "lng": 73.861309,
    "reportedAt": "2025-07-24"
  },
  {
    "id": "ISS-054",
    "title": "Streetlight not working",
    "description": "Affecting water supply in nearby areas.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 56,
    "status": "unresolved",
    "lat": 18.532289,
    "lng": 73.850365,
    "reportedAt": "2025-06-02"
  },
  {
    "id": "ISS-055",
    "title": "Water leakage",
    "description": "Causing power disruptions.",
    "category": "Sanitation",
    "severity": "high",
    "upvotes": 42,
    "status": "in-progress",
    "lat": 18.527902,
    "lng": 73.851316,
    "reportedAt": "2025-06-25"
  },
  {
    "id": "ISS-056",
    "title": "Damaged traffic sign",
    "description": "Problem persists for weeks without resolution.",
    "category": "Water Supply",
    "severity": "medium",
    "upvotes": 12,
    "status": "unresolved",
    "lat": 18.521482,
    "lng": 73.850426,
    "reportedAt": "2025-07-13"
  },
  {
    "id": "ISS-057",
    "title": "Accumulated debris",
    "description": "Affecting water supply in nearby areas.",
    "category": "Water Supply",
    "severity": "critical",
    "upvotes": 64,
    "status": "unresolved",
    "lat": 18.539942,
    "lng": 73.85841,
    "reportedAt": "2025-05-06"
  },
  {
    "id": "ISS-058",
    "title": "Damaged traffic sign",
    "description": "Problem persists for weeks without resolution.",
    "category": "Sanitation",
    "severity": "high",
    "upvotes": 59,
    "status": "in-progress",
    "lat": 18.52373,
    "lng": 73.862678,
    "reportedAt": "2025-05-02"
  },
  {
    "id": "ISS-059",
    "title": "Drinking water contamination",
    "description": "Reported multiple times by residents.",
    "category": "Roads",
    "severity": "low",
    "upvotes": 65,
    "status": "in-progress",
    "lat": 18.526785,
    "lng": 73.854727,
    "reportedAt": "2025-06-01"
  },
  {
    "id": "ISS-060",
    "title": "Broken water pipeline",
    "description": "Creating hygiene and sanitation issues.",
    "category": "Electricity",
    "severity": "critical",
    "upvotes": 49,
    "status": "unresolved",
    "lat": 18.532166,
    "lng": 73.860209,
    "reportedAt": "2025-06-04"
  },
  {
    "id": "ISS-061",
    "title": "Pothole on road",
    "description": "Resulting in foul smell in locality.",
    "category": "Electricity",
    "severity": "low",
    "upvotes": 45,
    "status": "in-progress",
    "lat": 18.527272,
    "lng": 73.864092,
    "reportedAt": "2025-08-25"
  },
  {
    "id": "ISS-062",
    "title": "Illegal dumping",
    "description": "Causing power disruptions.",
    "category": "Electricity",
    "severity": "high",
    "upvotes": 86,
    "status": "resolved",
    "lat": 18.531358,
    "lng": 73.864657,
    "reportedAt": "2025-08-03"
  },
  {
    "id": "ISS-063",
    "title": "Signal malfunction",
    "description": "Leading to traffic congestion.",
    "category": "Electricity",
    "severity": "medium",
    "upvotes": 46,
    "status": "resolved",
    "lat": 18.538335,
    "lng": 73.852935,
    "reportedAt": "2025-08-29"
  },
  {
    "id": "ISS-064",
    "title": "Leaking tanker",
    "description": "Affecting water supply in nearby areas.",
    "category": "Electricity",
    "severity": "high",
    "upvotes": 92,
    "status": "unresolved",
    "lat": 18.536264,
    "lng": 73.856657,
    "reportedAt": "2025-07-31"
  },
  {
    "id": "ISS-065",
    "title": "Signal malfunction",
    "description": "Leading to traffic congestion.",
    "category": "Roads",
    "severity": "high",
    "upvotes": 46,
    "status": "resolved",
    "lat": 18.521342,
    "lng": 73.853451,
    "reportedAt": "2025-07-11"
  },
  {
    "id": "ISS-066",
    "title": "Transformer sparks",
    "description": "Posing a risk to pedestrians.",
    "category": "Water Supply",
    "severity": "high",
    "upvotes": 16,
    "status": "resolved",
    "lat": 18.533471,
    "lng": 73.860054,
    "reportedAt": "2025-08-16"
  },
  {
    "id": "ISS-067",
    "title": "Overhead wire hazard",
    "description": "Causing safety concerns for residents.",
    "category": "Electricity",
    "severity": "high",
    "upvotes": 60,
    "status": "unresolved",
    "lat": 18.528866,
    "lng": 73.852991,
    "reportedAt": "2025-05-25"
  },
  {
    "id": "ISS-068",
    "title": "Fallen tree blocking road",
    "description": "Posing a risk to pedestrians.",
    "category": "Roads",
    "severity": "critical",
    "upvotes": 86,
    "status": "unresolved",
    "lat": 18.529593,
    "lng": 73.855363,
    "reportedAt": "2025-09-19"
  },
  {
    "id": "ISS-069",
    "title": "Signal malfunction",
    "description": "Posing a risk to pedestrians.",
    "category": "Roads",
    "severity": "high",
    "upvotes": 34,
    "status": "in-progress",
    "lat": 18.529824,
    "lng": 73.867354,
    "reportedAt": "2025-07-31"
  },
  {
    "id": "ISS-070",
    "title": "Leaking tanker",
    "description": "Resulting in foul smell in locality.",
    "category": "Water Supply",
    "severity": "high",
    "upvotes": 62,
    "status": "resolved",
    "lat": 18.535206,
    "lng": 73.858837,
    "reportedAt": "2025-03-26"
  }
];

export const statusColor = {
  "unresolved": "red",
  "in-progress": "orange",
  "resolved": "green"
};